from __future__ import annotations


INDIA_LARGECAP_TICKERS = (
    "ADANIENT.NS",
    "ADANIPORTS.NS",
    "APOLLOHOSP.NS",
    "ASIANPAINT.NS",
    "AXISBANK.NS",
    "BAJAJ-AUTO.NS",
    "BAJAJFINSV.NS",
    "BAJFINANCE.NS",
    "BEL.NS",
    "BHARTIARTL.NS",
    "CIPLA.NS",
    "COALINDIA.NS",
    "DIVISLAB.NS",
    "DRREDDY.NS",
    "EICHERMOT.NS",
    "ETERNAL.NS",
    "GRASIM.NS",
    "HCLTECH.NS",
    "HDFCBANK.NS",
    "HEROMOTOCO.NS",
    "HINDALCO.NS",
    "HINDUNILVR.NS",
    "ICICIBANK.NS",
    "INDUSINDBK.NS",
    "INFY.NS",
    "ITC.NS",
    "JIOFIN.NS",
    "JSWSTEEL.NS",
    "KOTAKBANK.NS",
    "LT.NS",
    "M&M.NS",
    "MARUTI.NS",
    "NESTLEIND.NS",
    "NTPC.NS",
    "ONGC.NS",
    "PIDILITIND.NS",
    "POWERGRID.NS",
    "RELIANCE.NS",
    "SBIN.NS",
    "SHRIRAMFIN.NS",
    "SUNPHARMA.NS",
    "TATACONSUM.NS",
    "TATAMOTORS.NS",
    "TATASTEEL.NS",
    "TCS.NS",
    "TECHM.NS",
    "TITAN.NS",
    "TRENT.NS",
    "ULTRACEMCO.NS",
    "WIPRO.NS",
)


BANKING_LEADERS_TICKERS = (
    "AXISBANK.NS",
    "AUBANK.NS",
    "BANDHANBNK.NS",
    "BANKBARODA.NS",
    "FEDERALBNK.NS",
    "HDFCBANK.NS",
    "ICICIBANK.NS",
    "IDFCFIRSTB.NS",
    "INDUSINDBK.NS",
    "KOTAKBANK.NS",
    "PNB.NS",
    "SBIN.NS",
    "SHRIRAMFIN.NS",
)


IT_LEADERS_TICKERS = (
    "HCLTECH.NS",
    "INFY.NS",
    "LTIM.NS",
    "MPHASIS.NS",
    "NAUKRI.NS",
    "OFSS.NS",
    "PERSISTENT.NS",
    "TCS.NS",
    "TECHM.NS",
    "WIPRO.NS",
)


UNIVERSE_CONFIG = {
    "india-largecap": {
        "label": "India Large-Cap Leaders",
        "description": "Curated liquid NSE large-cap basket across financials, IT, energy, pharma, consumer, and industrials.",
        "members": INDIA_LARGECAP_TICKERS,
        "benchmark": "^NSEI",
        "benchmark_label": "Nifty 50",
    },
    "banking": {
        "label": "India Banking Leaders",
        "description": "Large Indian banks and finance names with active swing participation.",
        "members": BANKING_LEADERS_TICKERS,
        "benchmark": "^NSEBANK",
        "benchmark_label": "Nifty Bank",
    },
    "it": {
        "label": "India IT Leaders",
        "description": "Major Indian technology and software stocks tracked on the NSE.",
        "members": IT_LEADERS_TICKERS,
        "benchmark": "^CNXIT",
        "benchmark_label": "Nifty IT",
    },
}
